os: linux
# 开启基于容器的Travis CI任务，让编译效率更高。
sudo: false         
# 定义构建环境
language: node_js
node_js:
  - "7"
# - "6"
# 必须的服务
services:
# 配置构建的必须条件
before_install:
- git config --global user.name "gottawonder"
- git config --global user.email "gottawonder@163.com"
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
# 进行构建
# install步骤用来构建并且启动我们的容器。
install:
- nvm install node
- pip install coverage
# 安装测试的必须条件
# before_script步骤只是用来安装测试脚本所必需的库
before_script:
- nvm ls
- git version
- npm i install karma --save-dev
- npm i coveralls --save-dev
- cat ./coverage/lcov/lcov.info | ./node_modules/.bin/coveralls
# script用来执行我们的测试脚本。
# script:
after_script:
- npm run coveralls
# 每次构建的时候是否通知，如果不想收到通知邮箱，那就设置false吧
notifications:
- email: false
